version: '3.8'
services:
  text2nerf:
    image: nvcr.io/nvidia/pytorch:23.10-py3
    container_name: text2nerf
    ipc: host
    shm_size: 64G
    volumes:
      - /home/arthur:/home
    dns:
      - 8.8.8.8
    deploy:
      resources:
        reservations:
          cpus: '32.0'
